# Generated by Django 5.2.1 on 2025-05-29 09:28

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('visitor_details', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='visitor_status',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(max_length=255)),
            ],
            options={
                'verbose_name': 'Status',
                'verbose_name_plural': 'Statuses',
            },
        ),
        migrations.CreateModel(
            name='VisitPurposes',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('purpose', models.CharField(max_length=255)),
            ],
            options={
                'verbose_name': 'Visit Purpose',
                'verbose_name_plural': 'Visitor Purposes',
            },
        ),
        migrations.CreateModel(
            name='visitor_logs',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('log_datetime', models.DateTimeField(auto_now=True)),
                ('check_in', models.TimeField()),
                ('check_out', models.TimeField(blank=True, null=True)),
                ('visit_date', models.DateField()),
                ('visitor_details', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='visitor_details.visitordetails')),
                ('status', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='visitor_logs.visitor_status')),
                ('purpose', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='visitor_logs.visitpurposes')),
            ],
            options={
                'verbose_name': 'Visitor Log',
                'verbose_name_plural': 'Visitor Logs',
            },
        ),
    ]
