# Generated by Django 4.2 on 2025-05-26 11:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('visitor_details', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='visitor_status',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(max_length=255)),
            ],
            options={
                'verbose_name': 'Status',
                'verbose_name_plural': 'Statuses',
            },
        ),
        migrations.CreateModel(
            name='VisitPurposes',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('purpose', models.CharField(max_length=255)),
            ],
            options={
                'verbose_name': 'Visit Purpose',
                'verbose_name_plural': 'Visitor Purposes',
            },
        ),
        migrations.CreateModel(
            name='visitor_logs',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('check_in', models.TimeField()),
                ('check_out', models.TimeField(blank=True, null=True)),
                ('visit_date', models.DateField()),
                ('purpose', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='visitor_logs.visitpurposes')),
                ('status', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='visitor_logs.visitor_status')),
                ('visitor_details', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='visitor_details.visitordetails')),
            ],
            options={
                'verbose_name': 'Visitor Log',
                'verbose_name_plural': 'Visitor Logs',
            },
        ),
    ]
