# Generated by Django 5.2.1 on 2025-05-24 10:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('visitor_logs', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='visitor_logs',
            name='check_out',
            field=models.TimeField(blank=True, null=True),
        ),
    ]
