import 'package:safepass_frontend/src/dashboard/models/visitor_log_model.dart';

List<VisitorLog> get visitorLogList =>
    mockVisitorLogs.map((data) => VisitorLog.fromMap(data)).toList();

List<Map<String, dynamic>> get mockVisitorLogs => [
  {
    "name": "Alex Tamayo",
    "checkIn": "2:00 PM",
    "checkOut": "3:14 PM",
    "purpose": "Family Visit",
    "status": "Checked-out",
  },
  {
    "name": "Ryfiel Gonzales",
    "checkIn": "2:34 PM",
    "checkOut": "-",
    "purpose": "Legal Consultation",
    "status": "Denied",
  },
  {
    "name": "Heart Dela Cruz",
    "checkIn": "3:00 PM",
    "checkOut": "-",
    "purpose": "Medical Check-up",
    "status": "Checked-in",
  },
  {
    "name": "Clara Santos",
    "checkIn": "1:45 PM",
    "checkOut": "2:30 PM",
    "purpose": "Follow-up Visit",
    "status": "Checked-out",
  },
  {
    "name": "Miguel Reyes",
    "checkIn": "10:15 AM",
    "checkOut": "-",
    "purpose": "Legal Visit",
    "status": "Checked-in",
  },
  {
    "name": "Jasmine Cruz",
    "checkIn": "11:00 AM",
    "checkOut": "12:00 PM",
    "purpose": "Legal Consultation",
    "status": "Checked-out",
  },
  {
    "name": "Liam Navarro",
    "checkIn": "9:30 AM",
    "checkOut": "-",
    "purpose": "Medical Check-up",
    "status": "Checked-in",
  },
  {
    "name": "Nicole Lim",
    "checkIn": "3:20 PM",
    "checkOut": "-",
    "purpose": "Orientation for New Inmate Visitors",
    "status": "Checked-in",
  },
  {
    "name": "Carlos Mendoza",
    "checkIn": "2:00 PM",
    "checkOut": "2:45 PM",
    "purpose": "Family Visit",
    "status": "Checked-out",
  },
  {
    "name": "Tanya De Vera",
    "checkIn": "1:00 PM",
    "checkOut": "-",
    "purpose": "Facility Tour (Authorized)",
    "status": "Checked-in",
  },
  {
    "name": "Benjie Rios",
    "checkIn": "12:15 PM",
    "checkOut": "1:00 PM",
    "purpose": "Legal Briefing",
    "status": "Checked-out",
  },
  {
    "name": "Ava Bautista",
    "checkIn": "8:45 AM",
    "checkOut": "-",
    "purpose": "Counseling Session",
    "status": "Checked-in",
  },
  {
    "name": "Diego Villanueva",
    "checkIn": "4:10 PM",
    "checkOut": "5:00 PM",
    "purpose": "Medical Check-up",
    "status": "Checked-out",
  },
  {
    "name": "Isabel Santos",
    "checkIn": "9:00 AM",
    "checkOut": "9:45 AM",
    "purpose": "New Visitor Orientation",
    "status": "Checked-out",
  },
  {
    "name": "Nathaniel Cruz",
    "checkIn": "10:00 AM",
    "checkOut": "-",
    "purpose": "Follow-up Visit",
    "status": "Checked-in",
  },
  {
    "name": "Sophia Gutierrez",
    "checkIn": "11:30 AM",
    "checkOut": "-",
    "purpose": "Medical Check-up",
    "status": "Checked-in",
  },
  {
    "name": "Erik Fernando",
    "checkIn": "2:10 PM",
    "checkOut": "3:00 PM",
    "purpose": "Attorney Meeting",
    "status": "Checked-out",
  },
  {
    "name": "Melissa Sy",
    "checkIn": "3:45 PM",
    "checkOut": "-",
    "purpose": "Counseling Session",
    "status": "Checked-in",
  },
  {
    "name": "Jerome Pascual",
    "checkIn": "1:30 PM",
    "checkOut": "-",
    "purpose": "Facility Inspection",
    "status": "Checked-in",
  },
  {
    "name": "Bea Tan",
    "checkIn": "12:00 PM",
    "checkOut": "12:45 PM",
    "purpose": "Legal Assistance",
    "status": "Checked-out",
  },
];
