services:
  django_app:
    build: .
    image: safepass-backend:latest
    command: sh -c "python manage.py runserver_plus --cert-file cert/cert.pem --key-file cert/key.pem 0.0.0.0:8000"
    ports:
      - '8000:8000'
    volumes:
      - .:/safepass_backend
    environment:
      PYTHONPATH: .
      DJANGO_SETTINGS_MODULE: safepass_backend.settings
      PYTHONUNBUFFERED: 1

volumes:
  .:

