services:
  django_app:
    build: .
    image: safepass-backend:latest
    command: sh -c "python manage.py runserver 0.0.0.0:8000"
    ports:
      - '8000:8000'
    volumes:
      - .:/strativa_backend
