# Generated by Django 5.2.1 on 2025-05-29 09:28

import django.db.models.deletion
import django.utils.timezone
import visitor_details.models
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='IdTypes',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(max_length=255)),
                ('code', models.CharField(max_length=255, unique=True)),
            ],
            options={
                'verbose_name': 'ID Type',
                'verbose_name_plural': 'ID Types',
            },
        ),
        migrations.CreateModel(
            name='VisitorDetails',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('photo', models.ImageField(default='default_photo/no_photo.png', upload_to=visitor_details.models.VisitorDetails.custom_upload_to)),
                ('first_name', models.CharField(max_length=255)),
                ('middle_name', models.CharField(blank=True, max_length=255)),
                ('last_name', models.CharField(max_length=255)),
                ('full_name', models.CharField(max_length=765)),
                ('contact_number', models.CharField(max_length=11)),
                ('id_number', models.CharField(max_length=255)),
                ('status', models.CharField(choices=[('Approved', 'Approved'), ('Archived', 'Archived'), ('Denied', 'Denied')], default='Approved', max_length=255)),
                ('registration_date', models.DateTimeField(default=django.utils.timezone.now)),
                ('id_type', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='visitor_details.idtypes')),
            ],
            options={
                'verbose_name': 'Visitor Detail',
                'verbose_name_plural': 'Visitor Details',
                'constraints': [models.UniqueConstraint(fields=('id_type', 'id_number'), name='unique_id_type_and_id_number')],
            },
        ),
    ]
