# Generated by Django 5.2.1 on 2025-05-17 10:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('visitor_details', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='idtypes',
            options={'verbose_name': 'ID Type', 'verbose_name_plural': 'ID Types'},
        ),
        migrations.AlterModelOptions(
            name='visitordetails',
            options={'verbose_name': 'Visitor Detail', 'verbose_name_plural': 'Visitor Details'},
        ),
        migrations.AlterModelOptions(
            name='visitpurposes',
            options={'verbose_name': 'Visit Purpose', 'verbose_name_plural': 'Visitor Purposes'},
        ),
    ]
