# Generated by Django 5.2.1 on 2025-05-26 09:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('visitor_details', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='visitordetails',
            name='photo',
            field=models.ImageField(blank=True, null=True, upload_to='visitor_photos'),
        ),
    ]
