# Generated by Django 5.2.1 on 2025-05-17 10:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('visitor_details', '0002_alter_idtypes_options_alter_visitordetails_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='visitordetails',
            name='full_name',
            field=models.CharField(default='', max_length=255),
        ),
    ]
